# Allows you to toggle specific optimizations that don't have full vanilla parity.
# These settings will only take effect after server restarts.

# Prevents many different lagspikes caused by loading chunks synchronously.
# This for example causes maps to only update loaded chunks, which depending on the viewdistance can be a smaller radius than vanilla.
reduce-sync-loads: true
# Can significantly reduce the time spent on chunk iteration by only updating the ticking chunks list each second, rather than each tick.
# This is especially useful for servers with a high playercount and / or viewdistance.
# Note: This setting is incompatible with Moonrise.
cache-ticking-chunks: true
# Optimizes command block executions by caching parsed commands.
# Command parsing is a relatively expensive operation. By caching it we avoid parsing the same command every time it is executed.
optimize-command-blocks: false
# Can significantly reduce time spent on mobspawning, but isn't as accurate as vanilla on biome borders.
# This may cause mobs from another biome to spawn a few blocks across a biome border (this does not affect structure spawning!).
fast-biome-lookups: false
# Fluid random ticks, like lava spreading fire, are run twice each game tick.
# Enabling this will cancel the 'duplicate' second fluid tick, but this may cause slight behavior changes.
cancel-duplicate-fluid-ticks: false
